name: 'Someday, I learn'
description: 'Send a cheatsheet to slack someday your learn'
inputs:
  CHEATSHEET_HOST:
    description: 'cheatsheet host'
    required: true
  SLACK_CHANNEL:
    description: 'slack channel name'
    required: false
  debug:
    description: 'debug flag'
    required: false
outputs:
  time: # output will be available to future steps
    description: 'Success'
runs:
  using: 'node12'
  main: 'dist/index.js'
